[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "https://axgrind.netlify.app/*"
  to = "https://axgrind.fit/:splat"
  status = 301
  force = true

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
