#!/bin/zsh
set -e

# Xcode Cloud only clones the git repo, so files generated by the web build
# and `npx cap sync` (ios/App/App/public, capacitor.config.json, config.xml)
# don't exist yet. Build them here before Xcode compiles the app.

cd "$CI_WORKSPACE"

if ! command -v node &> /dev/null; then
  brew install node
fi

npm install
npm run build

echo "--- debug: pwd and ios dir state before cap sync ---"
pwd
ls -la
ls -la ios || echo "no ios dir here"
cat capacitor.config.json || echo "no capacitor.config.json here"
echo "--- end debug ---"

npx cap sync ios
