#!/bin/zsh
set -e

# Xcode Cloud only clones the git repo, so files generated by the web build
# and `npx cap sync` (ios/App/App/public, capacitor.config.json, config.xml)
# don't exist yet. Build them here before Xcode compiles the app.
#
# Xcode Cloud runs this script with CWD already set to its own directory
# (ios/App/ci_scripts), not the repo root, and there's no reliable env var
# for the repo root — so derive it from this script's own location instead.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT"

if ! command -v node &> /dev/null; then
  brew install node
fi

npm install
npm run build
npx cap sync ios
